# Generated by Django 4.2.4 on 2025-06-04 00:29

# employees/migrations/0003_populate_user_field.py

from django.db import migrations, models
import random, string

def create_users_for_employees(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    Employee = apps.get_model('employees', 'Employee')

    for emp in Employee.objects.filter(user_id__isnull=True):
        base_username = emp.email.split('@')[0]
        username = base_username
        counter = 1
        # ensure unique username
        while User.objects.filter(username=username).exists():
            username = f"{base_username}{counter}"
            counter += 1

        random_password = "".join(random.choices(string.ascii_letters + string.digits, k=12))
        user = User.objects.create_user(
            username=username,
            email=emp.email,
            password=random_password
        )
        # Assign the newly created user to the employee
        emp.user_id = user.id
        emp.save()

class Migration(migrations.Migration):
    dependencies = [
        ('employees', '0002_employee_user'),
    ]

    operations = [
        migrations.RunPython(create_users_for_employees, reverse_code=migrations.RunPython.noop),
    ]

